# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-04 09:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobOpenings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('pretext', models.TextField(max_length=300)),
                ('slug', models.SlugField(editable=False, max_length=200)),
                ('text', models.TextField()),
                ('posted_on', models.DateTimeField()),
                ('expires_on', models.DateField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('modified_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('New', 'New'), ('Draft', 'Draft'), ('Published', 'Published'), ('Archived', 'Archived')], default='new', max_length=100)),
                ('views', models.IntegerField(default=0, editable=False)),
            ],
            options={
                'ordering': ['-posted_on'],
                'verbose_name_plural': 'Job Openings',
            },
        ),
    ]
