# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-04 10:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobopenings',
            options={'ordering': ['-published_date'], 'verbose_name_plural': 'Job Openings'},
        ),
        migrations.RemoveField(
            model_name='jobopenings',
            name='posted_on',
        ),
    ]
