# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-04 10:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_auto_20160504_1141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobopenings',
            old_name='text',
            new_name='body',
        ),
    ]
